[2022-12-30T20:33:48.814-0500] {processor.py:153} INFO - Started process (PID=23132) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:33:48.815-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:33:48.816-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:33:48.816-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:33:48.818-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:33:48.817-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 18
    bash_command= 'sh sql2csv.sh',
               ^
SyntaxError: invalid syntax
[2022-12-30T20:33:48.819-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:33:48.828-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.016 seconds
[2022-12-30T20:34:19.187-0500] {processor.py:153} INFO - Started process (PID=23185) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:34:19.190-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:34:19.191-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:34:19.191-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:34:19.197-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:34:19.195-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 18
    bash_command= 'sh sql2csv.sh',
               ^
SyntaxError: invalid syntax
[2022-12-30T20:34:19.197-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:34:19.215-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.033 seconds
[2022-12-30T20:34:49.787-0500] {processor.py:153} INFO - Started process (PID=23199) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:34:49.789-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:34:49.791-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:34:49.790-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:34:49.796-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:34:49.794-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 18
    bash_command= 'sh sql2csv.sh',
               ^
SyntaxError: invalid syntax
[2022-12-30T20:34:49.796-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:34:49.815-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.032 seconds
[2022-12-30T20:35:20.371-0500] {processor.py:153} INFO - Started process (PID=23216) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:35:20.373-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:35:20.375-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:35:20.374-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:35:20.379-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:35:20.377-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 18
    bash_command= 'sh sql2csv.sh',
               ^
SyntaxError: invalid syntax
[2022-12-30T20:35:20.380-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:35:20.396-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.029 seconds
[2022-12-30T20:35:30.474-0500] {processor.py:153} INFO - Started process (PID=23263) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:35:30.474-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:35:30.476-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:35:30.475-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:35:30.478-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:35:30.477-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
               ^
SyntaxError: invalid syntax
[2022-12-30T20:35:30.478-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:35:30.489-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.017 seconds
[2022-12-30T20:36:00.621-0500] {processor.py:153} INFO - Started process (PID=23273) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:00.622-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:36:00.623-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:36:00.623-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:00.627-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:36:00.626-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
               ^
SyntaxError: invalid syntax
[2022-12-30T20:36:00.627-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:00.642-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.024 seconds
[2022-12-30T20:36:08.869-0500] {processor.py:153} INFO - Started process (PID=23313) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:08.870-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:36:08.871-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:36:08.871-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:08.874-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:36:08.873-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:36:08.874-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:08.885-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.018 seconds
[2022-12-30T20:36:39.249-0500] {processor.py:153} INFO - Started process (PID=23318) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:39.251-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:36:39.252-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:36:39.252-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:39.256-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:36:39.255-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:36:39.257-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:36:39.274-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.030 seconds
[2022-12-30T20:37:09.828-0500] {processor.py:153} INFO - Started process (PID=23321) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:37:09.829-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:37:09.831-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:37:09.830-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:37:09.835-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:37:09.833-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:37:09.835-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:37:09.853-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.030 seconds
[2022-12-30T20:37:40.428-0500] {processor.py:153} INFO - Started process (PID=23325) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:37:40.429-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:37:40.431-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:37:40.430-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:37:40.435-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:37:40.433-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:37:40.436-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:37:40.454-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.030 seconds
[2022-12-30T20:38:10.702-0500] {processor.py:153} INFO - Started process (PID=23327) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:38:10.703-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:38:10.705-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:38:10.704-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:38:10.709-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:38:10.708-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:38:10.710-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:38:10.728-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.031 seconds
[2022-12-30T20:38:40.923-0500] {processor.py:153} INFO - Started process (PID=23330) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:38:40.925-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:38:40.926-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:38:40.926-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:38:40.931-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:38:40.930-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:38:40.932-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:38:40.948-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.029 seconds
[2022-12-30T20:39:11.145-0500] {processor.py:153} INFO - Started process (PID=23334) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:39:11.146-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:39:11.148-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:39:11.147-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:39:11.152-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:39:11.150-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:39:11.153-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:39:11.172-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.031 seconds
[2022-12-30T20:39:41.378-0500] {processor.py:153} INFO - Started process (PID=23338) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:39:41.380-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:39:41.381-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:39:41.380-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:39:41.385-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:39:41.384-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:39:41.386-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:39:41.406-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.032 seconds
[2022-12-30T20:40:11.547-0500] {processor.py:153} INFO - Started process (PID=23342) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:40:11.548-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:40:11.550-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:40:11.549-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:40:11.555-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:40:11.552-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:40:11.559-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:40:11.582-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.039 seconds
[2022-12-30T20:40:41.722-0500] {processor.py:153} INFO - Started process (PID=23346) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:40:41.723-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:40:41.724-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:40:41.724-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:40:41.728-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:40:41.727-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:40:41.729-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:40:41.746-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.029 seconds
[2022-12-30T20:41:11.897-0500] {processor.py:153} INFO - Started process (PID=23350) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:41:11.898-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:41:11.899-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:41:11.899-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:41:11.903-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:41:11.902-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:41:11.904-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:41:11.921-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.029 seconds
[2022-12-30T20:41:42.082-0500] {processor.py:153} INFO - Started process (PID=23354) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:41:42.083-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:41:42.085-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:41:42.084-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:41:42.088-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:41:42.087-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:41:42.089-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:41:42.106-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.028 seconds
[2022-12-30T20:42:12.269-0500] {processor.py:153} INFO - Started process (PID=23356) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:42:12.271-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:42:12.272-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:42:12.272-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:42:12.276-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:42:12.275-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:42:12.276-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:42:12.293-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.028 seconds
[2022-12-30T20:42:42.448-0500] {processor.py:153} INFO - Started process (PID=23359) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:42:42.450-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:42:42.451-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:42:42.451-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:42:42.455-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:42:42.454-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:42:42.456-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:42:42.472-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.028 seconds
[2022-12-30T20:43:12.624-0500] {processor.py:153} INFO - Started process (PID=23362) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:43:12.626-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:43:12.627-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:43:12.627-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:43:12.630-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:43:12.629-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:43:12.631-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:43:12.647-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.026 seconds
[2022-12-30T20:43:42.805-0500] {processor.py:153} INFO - Started process (PID=23366) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:43:42.807-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:43:42.808-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:43:42.808-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:43:42.812-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:43:42.810-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:43:42.812-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:43:42.830-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.030 seconds
[2022-12-30T20:44:12.991-0500] {processor.py:153} INFO - Started process (PID=23370) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:44:12.993-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:44:12.994-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:44:12.994-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:44:12.998-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:44:12.997-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:44:12.999-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:44:13.016-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.028 seconds
[2022-12-30T20:44:43.168-0500] {processor.py:153} INFO - Started process (PID=23373) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:44:43.170-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:44:43.171-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:44:43.171-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:44:43.175-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:44:43.173-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:44:43.175-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:44:43.192-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.028 seconds
[2022-12-30T20:45:13.410-0500] {processor.py:153} INFO - Started process (PID=23406) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:45:13.412-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:45:13.414-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:45:13.413-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:45:13.419-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:45:13.417-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:45:13.419-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:45:13.437-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.031 seconds
[2022-12-30T20:45:43.637-0500] {processor.py:153} INFO - Started process (PID=23502) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:45:43.639-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:45:43.640-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:45:43.640-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:45:43.645-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:45:43.643-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:45:43.646-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:45:43.663-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.030 seconds
[2022-12-30T20:46:13.847-0500] {processor.py:153} INFO - Started process (PID=23524) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:46:13.849-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:46:13.851-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:46:13.850-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:46:13.855-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:46:13.853-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:46:13.855-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:46:13.873-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.030 seconds
[2022-12-30T20:46:44.337-0500] {processor.py:153} INFO - Started process (PID=23572) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:46:44.338-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:46:44.340-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:46:44.339-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:46:44.345-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:46:44.344-0500] {dagbag.py:343} ERROR - Failed to import: /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py", line 24
    bash_command="""R -e "shiny::runApp('ui/app.r', port = 3838)""""
                                                                   ^
SyntaxError: EOL while scanning string literal
[2022-12-30T20:46:44.346-0500] {processor.py:755} WARNING - No viable dags retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:46:44.363-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.030 seconds
[2022-12-30T20:47:13.926-0500] {processor.py:153} INFO - Started process (PID=23634) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:47:13.926-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:47:13.928-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:13.927-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:47:13.941-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:13.940-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:47:13.948-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:47:13.989-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:13.989-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:47:14.004-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:14.004-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-01-01T00:00:00+00:00, run_after=2022-01-02T00:00:00+00:00
[2022-12-30T20:47:14.020-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.097 seconds
[2022-12-30T20:47:44.172-0500] {processor.py:153} INFO - Started process (PID=23669) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:47:44.174-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:47:44.175-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:44.175-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:47:44.199-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:44.197-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:47:44.208-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:47:44.233-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:44.232-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:47:44.249-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:47:44.248-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-01-01T00:00:00+00:00, run_after=2022-01-02T00:00:00+00:00
[2022-12-30T20:47:44.261-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.093 seconds
[2022-12-30T20:48:14.791-0500] {processor.py:153} INFO - Started process (PID=23674) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:48:14.793-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:48:14.797-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:14.795-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:48:14.826-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:14.824-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:48:14.837-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:48:14.869-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:14.868-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:48:14.885-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:14.885-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-01-01T00:00:00+00:00, run_after=2022-01-02T00:00:00+00:00
[2022-12-30T20:48:14.898-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.111 seconds
[2022-12-30T20:48:46.367-0500] {processor.py:153} INFO - Started process (PID=23756) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:48:46.368-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:48:46.368-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:46.368-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:48:46.381-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:46.380-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:48:46.387-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:48:46.407-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:46.407-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:48:46.424-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:48:46.424-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-01-08T00:00:00+00:00, run_after=2022-01-09T00:00:00+00:00
[2022-12-30T20:48:46.437-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.073 seconds
[2022-12-30T20:49:16.953-0500] {processor.py:153} INFO - Started process (PID=23915) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:49:16.954-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:49:16.955-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:16.955-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:49:16.966-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:16.965-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:49:16.967-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:16.966-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ui/run_app.sh
[2022-12-30T20:49:16.972-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:49:17.014-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:17.013-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:49:17.029-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:17.028-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-01-16T00:00:00+00:00, run_after=2022-01-17T00:00:00+00:00
[2022-12-30T20:49:17.044-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.092 seconds
[2022-12-30T20:49:47.576-0500] {processor.py:153} INFO - Started process (PID=23941) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:49:47.577-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:49:47.578-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:47.578-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:49:47.589-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:47.588-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:49:47.590-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:47.589-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ui/run_app.sh
[2022-12-30T20:49:47.595-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:49:47.610-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:47.609-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:49:47.625-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:49:47.625-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-01-19T00:00:00+00:00, run_after=2022-01-20T00:00:00+00:00
[2022-12-30T20:49:47.639-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.064 seconds
[2022-12-30T20:50:18.334-0500] {processor.py:153} INFO - Started process (PID=24013) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:50:18.335-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:50:18.335-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:18.335-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:50:18.346-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:18.345-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:50:18.347-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:18.346-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ui/run_app.sh
[2022-12-30T20:50:18.352-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:50:18.367-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:18.367-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:50:18.383-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:18.383-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-01-30T00:00:00+00:00, run_after=2022-01-31T00:00:00+00:00
[2022-12-30T20:50:18.396-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.064 seconds
[2022-12-30T20:50:48.563-0500] {processor.py:153} INFO - Started process (PID=24082) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:50:48.565-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:50:48.566-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:48.566-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:50:48.586-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:48.585-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:50:48.587-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:48.586-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ui/run_app.sh
[2022-12-30T20:50:48.595-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:50:48.613-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:48.613-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:50:48.629-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:50:48.629-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-02-10T00:00:00+00:00, run_after=2022-02-11T00:00:00+00:00
[2022-12-30T20:50:48.641-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.082 seconds
[2022-12-30T20:51:18.717-0500] {processor.py:153} INFO - Started process (PID=24159) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:51:18.718-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:51:18.718-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:18.718-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:51:18.730-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:18.729-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:51:18.730-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:18.730-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ui/run_app.sh
[2022-12-30T20:51:18.735-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:51:18.750-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:18.750-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:51:18.766-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:18.766-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-02-22T00:00:00+00:00, run_after=2022-02-23T00:00:00+00:00
[2022-12-30T20:51:18.780-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.065 seconds
[2022-12-30T20:51:49.167-0500] {processor.py:153} INFO - Started process (PID=24229) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:51:49.168-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:51:49.169-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:49.168-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:51:49.180-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:49.179-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:51:49.181-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:49.180-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ui/run_app.sh
[2022-12-30T20:51:49.185-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:51:49.200-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:49.200-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:51:49.216-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:51:49.216-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-03-05T00:00:00+00:00, run_after=2022-03-06T00:00:00+00:00
[2022-12-30T20:51:49.229-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.064 seconds
[2022-12-30T20:52:20.783-0500] {processor.py:153} INFO - Started process (PID=24344) to work on /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:52:20.784-0500] {processor.py:743} INFO - Processing file /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py for tasks to queue
[2022-12-30T20:52:20.785-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:52:20.784-0500] {dagbag.py:538} INFO - Filling up the DagBag from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:52:20.796-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:52:20.795-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:52:20.796-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:52:20.796-0500] {abstractoperator.py:183} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 181, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh ui/run_app.sh
[2022-12-30T20:52:20.801-0500] {processor.py:753} INFO - DAG(s) dict_keys(['realtor_census_dashboard_etl']) retrieved from /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py
[2022-12-30T20:52:20.819-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:52:20.818-0500] {dag.py:2676} INFO - Sync 1 DAGs
[2022-12-30T20:52:20.837-0500] {logging_mixin.py:137} INFO - [2022-12-30T20:52:20.836-0500] {dag.py:3427} INFO - Setting next_dagrun for realtor_census_dashboard_etl to 2022-03-17T00:00:00+00:00, run_after=2022-03-18T00:00:00+00:00
[2022-12-30T20:52:20.850-0500] {processor.py:175} INFO - Processing /Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py took 0.069 seconds
