[2022-12-30T20:49:01.551-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: realtor_census_dashboard_etl.SQL_2_CSV scheduled__2022-01-11T00:00:00+00:00 [queued]>
[2022-12-30T20:49:01.559-0500] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: realtor_census_dashboard_etl.SQL_2_CSV scheduled__2022-01-11T00:00:00+00:00 [queued]>
[2022-12-30T20:49:01.559-0500] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-30T20:49:01.559-0500] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-30T20:49:01.559-0500] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-30T20:49:01.568-0500] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): SQL_2_CSV> on 2022-01-11 00:00:00+00:00
[2022-12-30T20:49:01.572-0500] {standard_task_runner.py:55} INFO - Started process 23833 to run task
[2022-12-30T20:49:01.576-0500] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'realtor_census_dashboard_etl', 'SQL_2_CSV', 'scheduled__2022-01-11T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', '/Users/miguelrondon/Desktop/CODE/Data Projects/Real-Estate-By-Census/dags/dag.py', '--cfg-path', '/var/folders/c5/lp6ccbfx3tq6qm5zscs07w980000gn/T/tmpatlvdry2']
[2022-12-30T20:49:01.577-0500] {standard_task_runner.py:83} INFO - Job 36: Subtask SQL_2_CSV
[2022-12-30T20:49:01.608-0500] {task_command.py:389} INFO - Running <TaskInstance: realtor_census_dashboard_etl.SQL_2_CSV scheduled__2022-01-11T00:00:00+00:00 [running]> on host miguels-macbook-pro-2.local
[2022-12-30T20:49:01.623-0500] {abstractoperator.py:596} ERROR - Exception rendering Jinja template for task 'SQL_2_CSV', field 'bash_command'. Template: 'sh sql2csv.sh'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:49:01.623-0500] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1497, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2119, in render_templates
    original_task.render_template_fields(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1196, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sh sql2csv.sh
[2022-12-30T20:49:01.627-0500] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=realtor_census_dashboard_etl, task_id=SQL_2_CSV, execution_date=20220111T000000, start_date=20221231T014901, end_date=20221231T014901
[2022-12-30T20:49:01.633-0500] {standard_task_runner.py:105} ERROR - Failed to execute job 36 for task SQL_2_CSV (sh sql2csv.sh; 23833)
[2022-12-30T20:49:01.638-0500] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-30T20:49:01.648-0500] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
